
```python
# .github/scripts/output.py

import json
from datetime import datetime

def write_shortlist(shortlisted: List[Dict], rejected: List[Dict], timestamp: str, entity_block: str):
    content = f"""# ZINOVA NOMAD – Auto-Generated Shortlist
> Generated by Autonomous Sourcing Agent v3.0
> **Timestamp:** {timestamp}

## ✅ Shortlisted Vendors (Top {len(shortlisted)})

| ID | Name | Source | Score | Key Strengths |
|----|------|--------|-------|----------------|
"""
    for i, v in enumerate(shortlisted[:10], 1):
        content += f"| S-{i:03d} | {v['name'][:30]} | {v.get('source', 'unknown')} | {v['score']} | Safety:{v['score_breakdown'].get('Safety',0)}/25 |\n"
    
    content += "\n## ❌ Rejected Vendors\n\n| Name | Source | Reason |\n|------|--------|--------|\n"
    for v in rejected[:15]:
        content += f"| {v['name'][:25]} | {v.get('source', 'unknown')} | {v.get('reason', 'Score too low')[:50]} |\n"
    
    content += entity_block
    # Also save JSON for machine processing
    with open("vendors/shortlist_data.json", "w") as f:
        json.dump({"shortlisted": shortlisted, "rejected": rejected, "timestamp": timestamp}, f, indent=2)

def write_rfq_email(vendor: Dict, entity_block: str):
    email_content = f"""To: {vendor.get('contact_email', 'sales@' + vendor.get('domain', 'example.com'))}
Subject: RFQ – Zinova Nomad IC-CPD Portable EV Charger

Dear {vendor['name']} Team,

Zinova is developing a portable Mode 2 EV charger (Nomad) for the Iranian market. 
Your company was identified through {vendor.get('source', 'marketplace')} as a potential OEM partner.

Please provide the following:

1. IEC 62752 certificate (with full test report)
2. Internal block diagram showing RCD and 6mA DC leakage detection
3. Factory address and production line photos/videos
4. MOQ, sample price (FOB), and lead time
5. Warranty terms and spare parts policy

Full technical datasheet is attached to this email.

Best regards,

{entity_block}
"""
    safe_name = vendor['name'].replace(' ', '_').replace('/', '_')
    with open(f"rfq_{safe_name}.md", "w") as f:
        f.write(email_content)
```

---
